baseurl: /
asseturl: /assets/
title: imzhi的博客
url: http://blog.imzhi.me/
timezone: Asia/Chongqing

paginate: 15
paginate_path: /page-:num
markdown: kramdown

author: imzhi
description:
keywords:

gems: [jekyll-paginate]

theme: jekyll-theme-cayman