baseurl: /
asseturl: /assets/
title: imzhi的个人博客
url: http://blog.imzhi.me/
timezone: Asia/Chongqing

paginate: 20
paginate_path: page-:num'
markdown: kramdown

author: imzhi的个人博客
description: imzhi的个人博客
keywords: imzhi,PHP,Web,技术,个人博客
